#ifndef CONVOLUTION28_OUTPUT_HPP_
#define CONVOLUTION28_OUTPUT_HPP_

#include "sliding_window.hpp"
#include "fork.hpp"
#include "conv.hpp"
#include "accum.hpp"
#include "glue.hpp"
#include "bias.hpp"

#define name        Convolution28_Output
#define NAME        CONVOLUTION28_OUTPUT
#define CONVOLUTION28_OUTPUT_ID   0

// parameters
#define CONVOLUTION28_OUTPUT_BATCH_SIZE    1
#define CONVOLUTION28_OUTPUT_ROWS          28
#define CONVOLUTION28_OUTPUT_COLS          28
#define CONVOLUTION28_OUTPUT_CHANNELS      1
#define CONVOLUTION28_OUTPUT_FILTERS       8
#define CONVOLUTION28_OUTPUT_GROUPS        1
#define CONVOLUTION28_OUTPUT_COARSE_IN     1
#define CONVOLUTION28_OUTPUT_COARSE_OUT    1
#define CONVOLUTION28_OUTPUT_COARSE_GROUP  1
#define CONVOLUTION28_OUTPUT_KERNEL_SIZE_X 5
#define CONVOLUTION28_OUTPUT_KERNEL_SIZE_Y 5
#define CONVOLUTION28_OUTPUT_FINE          25
#define CONVOLUTION28_OUTPUT_STRIDE_X      1
#define CONVOLUTION28_OUTPUT_STRIDE_Y      1

#define CONVOLUTION28_OUTPUT_HAS_BIAS 1

// coefficients
#define CONVOLUTION28_OUTPUT_WEIGHTS CONVOLUTION28_OUTPUT_FILTERS*DIVIDE(CONVOLUTION28_OUTPUT_CHANNELS,CONVOLUTION28_OUTPUT_GROUPS)*CONVOLUTION28_OUTPUT_KERNEL_SIZE_X*CONVOLUTION28_OUTPUT_KERNEL_SIZE_Y

// dimensions out
#define CONVOLUTION28_OUTPUT_ROWS_OUT     24
#define CONVOLUTION28_OUTPUT_COLS_OUT     24
#define CONVOLUTION28_OUTPUT_CHANNELS_OUT 8

// define data types
typedef ap_fixed<16,8,AP_RND>    Convolution28_Output_input_t;
typedef ap_fixed<16,8,AP_RND>  Convolution28_Output_output_t;
typedef ap_fixed<16,8,AP_RND>        Convolution28_Output_acc_t;
typedef ap_fixed<16,8,AP_RND>  Convolution28_Output_weight_t;
typedef ap_fixed<16,8,AP_RND>  Convolution28_Output_biases_t;

// SLIDING WINDOW
#define CONVOLUTION28_OUTPUT_SLIDING_WINDOW_BATCH_SIZE    1
#define CONVOLUTION28_OUTPUT_SLIDING_WINDOW_ROWS          28
#define CONVOLUTION28_OUTPUT_SLIDING_WINDOW_COLS          28
#define CONVOLUTION28_OUTPUT_SLIDING_WINDOW_CHANNELS      1
#define CONVOLUTION28_OUTPUT_SLIDING_WINDOW_KERNEL_SIZE_X 5
#define CONVOLUTION28_OUTPUT_SLIDING_WINDOW_KERNEL_SIZE_Y 5
#define CONVOLUTION28_OUTPUT_SLIDING_WINDOW_STRIDE_X      1
#define CONVOLUTION28_OUTPUT_SLIDING_WINDOW_STRIDE_Y      1
#define CONVOLUTION28_OUTPUT_SLIDING_WINDOW_PAD_LEFT      0
#define CONVOLUTION28_OUTPUT_SLIDING_WINDOW_PAD_RIGHT     0
#define CONVOLUTION28_OUTPUT_SLIDING_WINDOW_PAD_TOP       0
#define CONVOLUTION28_OUTPUT_SLIDING_WINDOW_PAD_BOTTOM    0

// FORK
#define CONVOLUTION28_OUTPUT_FORK_BATCH_SIZE    1
#define CONVOLUTION28_OUTPUT_FORK_ROWS          24
#define CONVOLUTION28_OUTPUT_FORK_COLS          24
#define CONVOLUTION28_OUTPUT_FORK_CHANNELS      1
#define CONVOLUTION28_OUTPUT_FORK_COARSE        1
#define CONVOLUTION28_OUTPUT_FORK_KERNEL_SIZE_X 5
#define CONVOLUTION28_OUTPUT_FORK_KERNEL_SIZE_Y 5

// CONV
#define CONVOLUTION28_OUTPUT_CONV_BATCH_SIZE          1
#define CONVOLUTION28_OUTPUT_CONV_ROWS                24
#define CONVOLUTION28_OUTPUT_CONV_COLS                24
#define CONVOLUTION28_OUTPUT_CONV_GROUPS              1
#define CONVOLUTION28_OUTPUT_CONV_CHANNELS            1
#define CONVOLUTION28_OUTPUT_CONV_FILTERS             8
#define CONVOLUTION28_OUTPUT_CONV_CHANNELS_PER_GROUP  1
#define CONVOLUTION28_OUTPUT_CONV_FILTERS_PER_GROUP   8
#define CONVOLUTION28_OUTPUT_CONV_KERNEL_SIZE_X       5
#define CONVOLUTION28_OUTPUT_CONV_KERNEL_SIZE_Y       5
#define CONVOLUTION28_OUTPUT_CONV_FINE                25
#define CONVOLUTION28_OUTPUT_CONV_INTERVAL            1

// ACCUM
#define CONVOLUTION28_OUTPUT_ACCUM_BATCH_SIZE         1
#define CONVOLUTION28_OUTPUT_ACCUM_ROWS               24
#define CONVOLUTION28_OUTPUT_ACCUM_COLS               24
#define CONVOLUTION28_OUTPUT_ACCUM_GROUPS             1
#define CONVOLUTION28_OUTPUT_ACCUM_CHANNELS           1
#define CONVOLUTION28_OUTPUT_ACCUM_FILTERS            8
#define CONVOLUTION28_OUTPUT_ACCUM_CHANNELS_PER_GROUP  1
#define CONVOLUTION28_OUTPUT_ACCUM_FILTERS_PER_GROUP   8

// GLUE
#define CONVOLUTION28_OUTPUT_GLUE_BATCH_SIZE   1
#define CONVOLUTION28_OUTPUT_GLUE_ROWS         24
#define CONVOLUTION28_OUTPUT_GLUE_COLS         24
#define CONVOLUTION28_OUTPUT_GLUE_FILTERS      8
#define CONVOLUTION28_OUTPUT_GLUE_FILTERS_PER_COARSE  8
#define CONVOLUTION28_OUTPUT_GLUE_COARSE_IN    1
#define CONVOLUTION28_OUTPUT_GLUE_COARSE_OUT   1
#define CONVOLUTION28_OUTPUT_GLUE_COARSE_GROUP 1

// BIAS
#define CONVOLUTION28_OUTPUT_BIAS_BATCH_SIZE   1
#define CONVOLUTION28_OUTPUT_BIAS_ROWS         24
#define CONVOLUTION28_OUTPUT_BIAS_COLS         24
//#define CONVOLUTION28_OUTPUT_BIAS_FILTERS      DIVIDE(CONVOLUTION28_OUTPUT_FILTERS, CONVOLUTION28_OUTPUT_COARSE_OUT*CONVOLUTION28_OUTPUT_WR_FACTOR)
#define CONVOLUTION28_OUTPUT_BIAS_FILTERS      8

/**
 * FUNCTION DEFINITION
 */

void Convolution28_Output(
    const Convolution28_Output_weight_t weights[CONVOLUTION28_OUTPUT_COARSE_IN*CONVOLUTION28_OUTPUT_COARSE_GROUP][CONVOLUTION28_OUTPUT_COARSE_OUT][DIVIDE(CONVOLUTION28_OUTPUT_WEIGHTS,CONVOLUTION28_OUTPUT_COARSE_IN*CONVOLUTION28_OUTPUT_COARSE_GROUP*CONVOLUTION28_OUTPUT_COARSE_OUT*CONVOLUTION28_OUTPUT_KERNEL_SIZE_X*CONVOLUTION28_OUTPUT_KERNEL_SIZE_Y)][CONVOLUTION28_OUTPUT_KERNEL_SIZE_X][CONVOLUTION28_OUTPUT_KERNEL_SIZE_Y],
#if CONVOLUTION28_OUTPUT_HAS_BIAS == 1
    const Convolution28_Output_biases_t biases[CONVOLUTION28_OUTPUT_COARSE_OUT][CONVOLUTION28_OUTPUT_BIAS_FILTERS],
#endif
    stream_t(Convolution28_Output_input_t)  in[CONVOLUTION28_OUTPUT_COARSE_IN*CONVOLUTION28_OUTPUT_COARSE_GROUP],
    stream_t(Convolution28_Output_output_t) out[CONVOLUTION28_OUTPUT_COARSE_OUT*CONVOLUTION28_OUTPUT_COARSE_GROUP],
    int mode
);

#undef name
#undef NAME
#endif
