#ifndef IMPORT_CONV4LAST_BIASADD_HPP_
#define IMPORT_CONV4LAST_BIASADD_HPP_

#include "sliding_window.hpp"
#include "fork.hpp"
#include "conv.hpp"
#include "accum.hpp"
#include "glue.hpp"
#include "bias.hpp"

#define name        import_conv4last_BiasAdd
#define NAME        IMPORT_CONV4LAST_BIASADD
#define IMPORT_CONV4LAST_BIASADD_ID   0

// parameters
#define IMPORT_CONV4LAST_BIASADD_BATCH_SIZE    1
#define IMPORT_CONV4LAST_BIASADD_ROWS          1
#define IMPORT_CONV4LAST_BIASADD_COLS          1
#define IMPORT_CONV4LAST_BIASADD_CHANNELS      1024
#define IMPORT_CONV4LAST_BIASADD_FILTERS       10
#define IMPORT_CONV4LAST_BIASADD_GROUPS        1
#define IMPORT_CONV4LAST_BIASADD_COARSE_IN     1
#define IMPORT_CONV4LAST_BIASADD_COARSE_OUT    1
#define IMPORT_CONV4LAST_BIASADD_COARSE_GROUP  1
#define IMPORT_CONV4LAST_BIASADD_KERNEL_SIZE_X 1
#define IMPORT_CONV4LAST_BIASADD_KERNEL_SIZE_Y 1
#define IMPORT_CONV4LAST_BIASADD_FINE          1
#define IMPORT_CONV4LAST_BIASADD_STRIDE_X      1
#define IMPORT_CONV4LAST_BIASADD_STRIDE_Y      1

#define IMPORT_CONV4LAST_BIASADD_HAS_BIAS 1

// coefficients
#define IMPORT_CONV4LAST_BIASADD_WEIGHTS IMPORT_CONV4LAST_BIASADD_FILTERS*DIVIDE(IMPORT_CONV4LAST_BIASADD_CHANNELS,IMPORT_CONV4LAST_BIASADD_GROUPS)*IMPORT_CONV4LAST_BIASADD_KERNEL_SIZE_X*IMPORT_CONV4LAST_BIASADD_KERNEL_SIZE_Y

// dimensions out
#define IMPORT_CONV4LAST_BIASADD_ROWS_OUT     1
#define IMPORT_CONV4LAST_BIASADD_COLS_OUT     1
#define IMPORT_CONV4LAST_BIASADD_CHANNELS_OUT 10

// define data types
typedef ap_fixed<16,8,AP_RND>    import_conv4last_BiasAdd_input_t;
typedef ap_fixed<16,8,AP_RND>  import_conv4last_BiasAdd_output_t;
typedef ap_fixed<16,8,AP_RND>        import_conv4last_BiasAdd_acc_t;
typedef ap_fixed<16,8,AP_RND>  import_conv4last_BiasAdd_weight_t;
typedef ap_fixed<16,8,AP_RND>  import_conv4last_BiasAdd_biases_t;

// SLIDING WINDOW
#define IMPORT_CONV4LAST_BIASADD_SLIDING_WINDOW_BATCH_SIZE    1
#define IMPORT_CONV4LAST_BIASADD_SLIDING_WINDOW_ROWS          1
#define IMPORT_CONV4LAST_BIASADD_SLIDING_WINDOW_COLS          1
#define IMPORT_CONV4LAST_BIASADD_SLIDING_WINDOW_CHANNELS      1024
#define IMPORT_CONV4LAST_BIASADD_SLIDING_WINDOW_KERNEL_SIZE_X 1
#define IMPORT_CONV4LAST_BIASADD_SLIDING_WINDOW_KERNEL_SIZE_Y 1
#define IMPORT_CONV4LAST_BIASADD_SLIDING_WINDOW_STRIDE_X      1
#define IMPORT_CONV4LAST_BIASADD_SLIDING_WINDOW_STRIDE_Y      1
#define IMPORT_CONV4LAST_BIASADD_SLIDING_WINDOW_PAD_LEFT      0
#define IMPORT_CONV4LAST_BIASADD_SLIDING_WINDOW_PAD_RIGHT     0
#define IMPORT_CONV4LAST_BIASADD_SLIDING_WINDOW_PAD_TOP       0
#define IMPORT_CONV4LAST_BIASADD_SLIDING_WINDOW_PAD_BOTTOM    0

// FORK
#define IMPORT_CONV4LAST_BIASADD_FORK_BATCH_SIZE    1
#define IMPORT_CONV4LAST_BIASADD_FORK_ROWS          1
#define IMPORT_CONV4LAST_BIASADD_FORK_COLS          1
#define IMPORT_CONV4LAST_BIASADD_FORK_CHANNELS      1024
#define IMPORT_CONV4LAST_BIASADD_FORK_COARSE        1
#define IMPORT_CONV4LAST_BIASADD_FORK_KERNEL_SIZE_X 1
#define IMPORT_CONV4LAST_BIASADD_FORK_KERNEL_SIZE_Y 1

// CONV
#define IMPORT_CONV4LAST_BIASADD_CONV_BATCH_SIZE          1
#define IMPORT_CONV4LAST_BIASADD_CONV_ROWS                1
#define IMPORT_CONV4LAST_BIASADD_CONV_COLS                1
#define IMPORT_CONV4LAST_BIASADD_CONV_GROUPS              1
#define IMPORT_CONV4LAST_BIASADD_CONV_CHANNELS            1024
#define IMPORT_CONV4LAST_BIASADD_CONV_FILTERS             10
#define IMPORT_CONV4LAST_BIASADD_CONV_CHANNELS_PER_GROUP  1024
#define IMPORT_CONV4LAST_BIASADD_CONV_FILTERS_PER_GROUP   10
#define IMPORT_CONV4LAST_BIASADD_CONV_KERNEL_SIZE_X       1
#define IMPORT_CONV4LAST_BIASADD_CONV_KERNEL_SIZE_Y       1
#define IMPORT_CONV4LAST_BIASADD_CONV_FINE                1
#define IMPORT_CONV4LAST_BIASADD_CONV_INTERVAL            1

// ACCUM
#define IMPORT_CONV4LAST_BIASADD_ACCUM_BATCH_SIZE         1
#define IMPORT_CONV4LAST_BIASADD_ACCUM_ROWS               1
#define IMPORT_CONV4LAST_BIASADD_ACCUM_COLS               1
#define IMPORT_CONV4LAST_BIASADD_ACCUM_GROUPS             1
#define IMPORT_CONV4LAST_BIASADD_ACCUM_CHANNELS           1024
#define IMPORT_CONV4LAST_BIASADD_ACCUM_FILTERS            10
#define IMPORT_CONV4LAST_BIASADD_ACCUM_CHANNELS_PER_GROUP  1024
#define IMPORT_CONV4LAST_BIASADD_ACCUM_FILTERS_PER_GROUP   10

// GLUE
#define IMPORT_CONV4LAST_BIASADD_GLUE_BATCH_SIZE   1
#define IMPORT_CONV4LAST_BIASADD_GLUE_ROWS         1
#define IMPORT_CONV4LAST_BIASADD_GLUE_COLS         1
#define IMPORT_CONV4LAST_BIASADD_GLUE_FILTERS      10
#define IMPORT_CONV4LAST_BIASADD_GLUE_FILTERS_PER_COARSE  10
#define IMPORT_CONV4LAST_BIASADD_GLUE_COARSE_IN    1
#define IMPORT_CONV4LAST_BIASADD_GLUE_COARSE_OUT   1
#define IMPORT_CONV4LAST_BIASADD_GLUE_COARSE_GROUP 1

// BIAS
#define IMPORT_CONV4LAST_BIASADD_BIAS_BATCH_SIZE   1
#define IMPORT_CONV4LAST_BIASADD_BIAS_ROWS         1
#define IMPORT_CONV4LAST_BIASADD_BIAS_COLS         1
//#define IMPORT_CONV4LAST_BIASADD_BIAS_FILTERS      DIVIDE(IMPORT_CONV4LAST_BIASADD_FILTERS, IMPORT_CONV4LAST_BIASADD_COARSE_OUT*IMPORT_CONV4LAST_BIASADD_WR_FACTOR)
#define IMPORT_CONV4LAST_BIASADD_BIAS_FILTERS      10

/**
 * FUNCTION DEFINITION
 */

void import_conv4last_BiasAdd(
    const import_conv4last_BiasAdd_weight_t weights[IMPORT_CONV4LAST_BIASADD_COARSE_IN*IMPORT_CONV4LAST_BIASADD_COARSE_GROUP][IMPORT_CONV4LAST_BIASADD_COARSE_OUT][DIVIDE(IMPORT_CONV4LAST_BIASADD_WEIGHTS,IMPORT_CONV4LAST_BIASADD_COARSE_IN*IMPORT_CONV4LAST_BIASADD_COARSE_GROUP*IMPORT_CONV4LAST_BIASADD_COARSE_OUT*IMPORT_CONV4LAST_BIASADD_KERNEL_SIZE_X*IMPORT_CONV4LAST_BIASADD_KERNEL_SIZE_Y)][IMPORT_CONV4LAST_BIASADD_KERNEL_SIZE_X][IMPORT_CONV4LAST_BIASADD_KERNEL_SIZE_Y],
#if IMPORT_CONV4LAST_BIASADD_HAS_BIAS == 1
    const import_conv4last_BiasAdd_biases_t biases[IMPORT_CONV4LAST_BIASADD_COARSE_OUT][IMPORT_CONV4LAST_BIASADD_BIAS_FILTERS],
#endif
    stream_t(import_conv4last_BiasAdd_input_t)  in[IMPORT_CONV4LAST_BIASADD_COARSE_IN*IMPORT_CONV4LAST_BIASADD_COARSE_GROUP],
    stream_t(import_conv4last_BiasAdd_output_t) out[IMPORT_CONV4LAST_BIASADD_COARSE_OUT*IMPORT_CONV4LAST_BIASADD_COARSE_GROUP],
    int mode
);

#undef name
#undef NAME
#endif
