#ifndef IMPORT_POOL2_MAXPOOL_HPP_
#define IMPORT_POOL2_MAXPOOL_HPP_

#include "sliding_window.hpp"
#include "pool.hpp"

#define name        import_pool2_MaxPool
#define NAME        IMPORT_POOL2_MAXPOOL
#define IMPORT_POOL2_MAXPOOL_ID   0

#define IMPORT_POOL2_MAXPOOL_BATCH_SIZE    1
#define IMPORT_POOL2_MAXPOOL_ROWS          14
#define IMPORT_POOL2_MAXPOOL_COLS          14
#define IMPORT_POOL2_MAXPOOL_CHANNELS      64
#define IMPORT_POOL2_MAXPOOL_COARSE        2
#define IMPORT_POOL2_MAXPOOL_KERNEL_SIZE_X 2
#define IMPORT_POOL2_MAXPOOL_KERNEL_SIZE_Y 2
#define IMPORT_POOL2_MAXPOOL_STRIDE_X      2
#define IMPORT_POOL2_MAXPOOL_STRIDE_Y      2
#define IMPORT_POOL2_MAXPOOL_FINE          1

#define IMPORT_POOL2_MAXPOOL_COARSE_IN    IMPORT_POOL2_MAXPOOL_COARSE
#define IMPORT_POOL2_MAXPOOL_COARSE_OUT   IMPORT_POOL2_MAXPOOL_COARSE

#define IMPORT_POOL2_MAXPOOL_ROWS_OUT     7
#define IMPORT_POOL2_MAXPOOL_COLS_OUT     7
#define IMPORT_POOL2_MAXPOOL_CHANNELS_OUT 64

// define the data type
typedef ap_fixed<16,8,AP_RND> import_pool2_MaxPool_data_t;
typedef import_pool2_MaxPool_data_t import_pool2_MaxPool_input_t;
typedef import_pool2_MaxPool_data_t import_pool2_MaxPool_output_t;

// SLIDING WINDOW
#define IMPORT_POOL2_MAXPOOL_SLIDING_WINDOW_BATCH_SIZE    1
#define IMPORT_POOL2_MAXPOOL_SLIDING_WINDOW_ROWS          14
#define IMPORT_POOL2_MAXPOOL_SLIDING_WINDOW_COLS          14
#define IMPORT_POOL2_MAXPOOL_SLIDING_WINDOW_CHANNELS      32
#define IMPORT_POOL2_MAXPOOL_SLIDING_WINDOW_KERNEL_SIZE_X 2
#define IMPORT_POOL2_MAXPOOL_SLIDING_WINDOW_KERNEL_SIZE_Y 2
#define IMPORT_POOL2_MAXPOOL_SLIDING_WINDOW_STRIDE_X      2
#define IMPORT_POOL2_MAXPOOL_SLIDING_WINDOW_STRIDE_Y      2
#define IMPORT_POOL2_MAXPOOL_SLIDING_WINDOW_PAD_LEFT      0
#define IMPORT_POOL2_MAXPOOL_SLIDING_WINDOW_PAD_RIGHT     0
#define IMPORT_POOL2_MAXPOOL_SLIDING_WINDOW_PAD_TOP       0
#define IMPORT_POOL2_MAXPOOL_SLIDING_WINDOW_PAD_BOTTOM    0

// POOL
#define IMPORT_POOL2_MAXPOOL_POOL_BATCH_SIZE   1
#define IMPORT_POOL2_MAXPOOL_POOL_ROWS         7
#define IMPORT_POOL2_MAXPOOL_POOL_COLS         7
#define IMPORT_POOL2_MAXPOOL_POOL_CHANNELS     32
#define IMPORT_POOL2_MAXPOOL_POOL_KERNEL_SIZE_X 2
#define IMPORT_POOL2_MAXPOOL_POOL_KERNEL_SIZE_Y 2
#define IMPORT_POOL2_MAXPOOL_POOL_FINE         1

/**
 * FUNCTION DEFINITION
 */

void import_pool2_MaxPool(
    stream_t(import_pool2_MaxPool_data_t) in[IMPORT_POOL2_MAXPOOL_COARSE],
    stream_t(import_pool2_MaxPool_data_t) out[IMPORT_POOL2_MAXPOOL_COARSE],
    int mode
);

#undef name
#undef NAME
#endif
