#ifndef IMPORT_CONV1FIRST_CONV2D_HPP_
#define IMPORT_CONV1FIRST_CONV2D_HPP_

#include "sliding_window.hpp"
#include "fork.hpp"
#include "conv.hpp"
#include "accum.hpp"
#include "glue.hpp"
#include "bias.hpp"

#define name        import_conv1first_Conv2D
#define NAME        IMPORT_CONV1FIRST_CONV2D
#define IMPORT_CONV1FIRST_CONV2D_ID   0

// parameters
#define IMPORT_CONV1FIRST_CONV2D_BATCH_SIZE    1
#define IMPORT_CONV1FIRST_CONV2D_ROWS          28
#define IMPORT_CONV1FIRST_CONV2D_COLS          28
#define IMPORT_CONV1FIRST_CONV2D_CHANNELS      1
#define IMPORT_CONV1FIRST_CONV2D_FILTERS       32
#define IMPORT_CONV1FIRST_CONV2D_GROUPS        1
#define IMPORT_CONV1FIRST_CONV2D_COARSE_IN     1
#define IMPORT_CONV1FIRST_CONV2D_COARSE_OUT    2
#define IMPORT_CONV1FIRST_CONV2D_COARSE_GROUP  1
#define IMPORT_CONV1FIRST_CONV2D_KERNEL_SIZE_X 5
#define IMPORT_CONV1FIRST_CONV2D_KERNEL_SIZE_Y 5
#define IMPORT_CONV1FIRST_CONV2D_FINE          5
#define IMPORT_CONV1FIRST_CONV2D_STRIDE_X      1
#define IMPORT_CONV1FIRST_CONV2D_STRIDE_Y      1

#define IMPORT_CONV1FIRST_CONV2D_HAS_BIAS 1

// coefficients
#define IMPORT_CONV1FIRST_CONV2D_WEIGHTS IMPORT_CONV1FIRST_CONV2D_FILTERS*DIVIDE(IMPORT_CONV1FIRST_CONV2D_CHANNELS,IMPORT_CONV1FIRST_CONV2D_GROUPS)*IMPORT_CONV1FIRST_CONV2D_KERNEL_SIZE_X*IMPORT_CONV1FIRST_CONV2D_KERNEL_SIZE_Y

// dimensions out
#define IMPORT_CONV1FIRST_CONV2D_ROWS_OUT     28
#define IMPORT_CONV1FIRST_CONV2D_COLS_OUT     28
#define IMPORT_CONV1FIRST_CONV2D_CHANNELS_OUT 32

// define data types
typedef ap_fixed<16,8,AP_RND>    import_conv1first_Conv2D_input_t;
typedef ap_fixed<16,8,AP_RND>  import_conv1first_Conv2D_output_t;
typedef ap_fixed<16,8,AP_RND>        import_conv1first_Conv2D_acc_t;
typedef ap_fixed<16,8,AP_RND>  import_conv1first_Conv2D_weight_t;
typedef ap_fixed<16,8,AP_RND>  import_conv1first_Conv2D_biases_t;

// SLIDING WINDOW
#define IMPORT_CONV1FIRST_CONV2D_SLIDING_WINDOW_BATCH_SIZE    1
#define IMPORT_CONV1FIRST_CONV2D_SLIDING_WINDOW_ROWS          28
#define IMPORT_CONV1FIRST_CONV2D_SLIDING_WINDOW_COLS          28
#define IMPORT_CONV1FIRST_CONV2D_SLIDING_WINDOW_CHANNELS      1
#define IMPORT_CONV1FIRST_CONV2D_SLIDING_WINDOW_KERNEL_SIZE_X 5
#define IMPORT_CONV1FIRST_CONV2D_SLIDING_WINDOW_KERNEL_SIZE_Y 5
#define IMPORT_CONV1FIRST_CONV2D_SLIDING_WINDOW_STRIDE_X      1
#define IMPORT_CONV1FIRST_CONV2D_SLIDING_WINDOW_STRIDE_Y      1
#define IMPORT_CONV1FIRST_CONV2D_SLIDING_WINDOW_PAD_LEFT      2
#define IMPORT_CONV1FIRST_CONV2D_SLIDING_WINDOW_PAD_RIGHT     2
#define IMPORT_CONV1FIRST_CONV2D_SLIDING_WINDOW_PAD_TOP       2
#define IMPORT_CONV1FIRST_CONV2D_SLIDING_WINDOW_PAD_BOTTOM    2

// FORK
#define IMPORT_CONV1FIRST_CONV2D_FORK_BATCH_SIZE    1
#define IMPORT_CONV1FIRST_CONV2D_FORK_ROWS          28
#define IMPORT_CONV1FIRST_CONV2D_FORK_COLS          28
#define IMPORT_CONV1FIRST_CONV2D_FORK_CHANNELS      1
#define IMPORT_CONV1FIRST_CONV2D_FORK_COARSE        2
#define IMPORT_CONV1FIRST_CONV2D_FORK_KERNEL_SIZE_X 5
#define IMPORT_CONV1FIRST_CONV2D_FORK_KERNEL_SIZE_Y 5

// CONV
#define IMPORT_CONV1FIRST_CONV2D_CONV_BATCH_SIZE          1
#define IMPORT_CONV1FIRST_CONV2D_CONV_ROWS                28
#define IMPORT_CONV1FIRST_CONV2D_CONV_COLS                28
#define IMPORT_CONV1FIRST_CONV2D_CONV_GROUPS              1
#define IMPORT_CONV1FIRST_CONV2D_CONV_CHANNELS            1
#define IMPORT_CONV1FIRST_CONV2D_CONV_FILTERS             16
#define IMPORT_CONV1FIRST_CONV2D_CONV_CHANNELS_PER_GROUP  1
#define IMPORT_CONV1FIRST_CONV2D_CONV_FILTERS_PER_GROUP   16
#define IMPORT_CONV1FIRST_CONV2D_CONV_KERNEL_SIZE_X       5
#define IMPORT_CONV1FIRST_CONV2D_CONV_KERNEL_SIZE_Y       5
#define IMPORT_CONV1FIRST_CONV2D_CONV_FINE                5
#define IMPORT_CONV1FIRST_CONV2D_CONV_INTERVAL            5

// ACCUM
#define IMPORT_CONV1FIRST_CONV2D_ACCUM_BATCH_SIZE         1
#define IMPORT_CONV1FIRST_CONV2D_ACCUM_ROWS               28
#define IMPORT_CONV1FIRST_CONV2D_ACCUM_COLS               28
#define IMPORT_CONV1FIRST_CONV2D_ACCUM_GROUPS             1
#define IMPORT_CONV1FIRST_CONV2D_ACCUM_CHANNELS           1
#define IMPORT_CONV1FIRST_CONV2D_ACCUM_FILTERS            16
#define IMPORT_CONV1FIRST_CONV2D_ACCUM_CHANNELS_PER_GROUP  1
#define IMPORT_CONV1FIRST_CONV2D_ACCUM_FILTERS_PER_GROUP   16

// GLUE
#define IMPORT_CONV1FIRST_CONV2D_GLUE_BATCH_SIZE   1
#define IMPORT_CONV1FIRST_CONV2D_GLUE_ROWS         28
#define IMPORT_CONV1FIRST_CONV2D_GLUE_COLS         28
#define IMPORT_CONV1FIRST_CONV2D_GLUE_FILTERS      32
#define IMPORT_CONV1FIRST_CONV2D_GLUE_FILTERS_PER_COARSE  16
#define IMPORT_CONV1FIRST_CONV2D_GLUE_COARSE_IN    1
#define IMPORT_CONV1FIRST_CONV2D_GLUE_COARSE_OUT   2
#define IMPORT_CONV1FIRST_CONV2D_GLUE_COARSE_GROUP 1

// BIAS
#define IMPORT_CONV1FIRST_CONV2D_BIAS_BATCH_SIZE   1
#define IMPORT_CONV1FIRST_CONV2D_BIAS_ROWS         28
#define IMPORT_CONV1FIRST_CONV2D_BIAS_COLS         28
//#define IMPORT_CONV1FIRST_CONV2D_BIAS_FILTERS      DIVIDE(IMPORT_CONV1FIRST_CONV2D_FILTERS, IMPORT_CONV1FIRST_CONV2D_COARSE_OUT*IMPORT_CONV1FIRST_CONV2D_WR_FACTOR)
#define IMPORT_CONV1FIRST_CONV2D_BIAS_FILTERS      16

/**
 * FUNCTION DEFINITION
 */

void import_conv1first_Conv2D(
    const import_conv1first_Conv2D_weight_t weights[IMPORT_CONV1FIRST_CONV2D_COARSE_IN*IMPORT_CONV1FIRST_CONV2D_COARSE_GROUP][IMPORT_CONV1FIRST_CONV2D_COARSE_OUT][DIVIDE(IMPORT_CONV1FIRST_CONV2D_WEIGHTS,IMPORT_CONV1FIRST_CONV2D_COARSE_IN*IMPORT_CONV1FIRST_CONV2D_COARSE_GROUP*IMPORT_CONV1FIRST_CONV2D_COARSE_OUT*IMPORT_CONV1FIRST_CONV2D_KERNEL_SIZE_X*IMPORT_CONV1FIRST_CONV2D_KERNEL_SIZE_Y)][IMPORT_CONV1FIRST_CONV2D_KERNEL_SIZE_X][IMPORT_CONV1FIRST_CONV2D_KERNEL_SIZE_Y],
#if IMPORT_CONV1FIRST_CONV2D_HAS_BIAS == 1
    const import_conv1first_Conv2D_biases_t biases[IMPORT_CONV1FIRST_CONV2D_COARSE_OUT][IMPORT_CONV1FIRST_CONV2D_BIAS_FILTERS],
#endif
    stream_t(import_conv1first_Conv2D_input_t)  in[IMPORT_CONV1FIRST_CONV2D_COARSE_IN*IMPORT_CONV1FIRST_CONV2D_COARSE_GROUP],
    stream_t(import_conv1first_Conv2D_output_t) out[IMPORT_CONV1FIRST_CONV2D_COARSE_OUT*IMPORT_CONV1FIRST_CONV2D_COARSE_GROUP],
    int mode
);

#undef name
#undef NAME
#endif
