#ifndef IMPORT_POOL1_MAXPOOL_HPP_
#define IMPORT_POOL1_MAXPOOL_HPP_

#include "sliding_window.hpp"
#include "pool.hpp"

#define name        import_pool1_MaxPool
#define NAME        IMPORT_POOL1_MAXPOOL
#define IMPORT_POOL1_MAXPOOL_ID   0

#define IMPORT_POOL1_MAXPOOL_BATCH_SIZE    1
#define IMPORT_POOL1_MAXPOOL_ROWS          28
#define IMPORT_POOL1_MAXPOOL_COLS          28
#define IMPORT_POOL1_MAXPOOL_CHANNELS      32
#define IMPORT_POOL1_MAXPOOL_COARSE        2
#define IMPORT_POOL1_MAXPOOL_KERNEL_SIZE_X 2
#define IMPORT_POOL1_MAXPOOL_KERNEL_SIZE_Y 2
#define IMPORT_POOL1_MAXPOOL_STRIDE_X      2
#define IMPORT_POOL1_MAXPOOL_STRIDE_Y      2
#define IMPORT_POOL1_MAXPOOL_FINE          1

#define IMPORT_POOL1_MAXPOOL_COARSE_IN    IMPORT_POOL1_MAXPOOL_COARSE
#define IMPORT_POOL1_MAXPOOL_COARSE_OUT   IMPORT_POOL1_MAXPOOL_COARSE

#define IMPORT_POOL1_MAXPOOL_ROWS_OUT     14
#define IMPORT_POOL1_MAXPOOL_COLS_OUT     14
#define IMPORT_POOL1_MAXPOOL_CHANNELS_OUT 32

// define the data type
typedef ap_fixed<16,8,AP_RND> import_pool1_MaxPool_data_t;
typedef import_pool1_MaxPool_data_t import_pool1_MaxPool_input_t;
typedef import_pool1_MaxPool_data_t import_pool1_MaxPool_output_t;

// SLIDING WINDOW
#define IMPORT_POOL1_MAXPOOL_SLIDING_WINDOW_BATCH_SIZE    1
#define IMPORT_POOL1_MAXPOOL_SLIDING_WINDOW_ROWS          28
#define IMPORT_POOL1_MAXPOOL_SLIDING_WINDOW_COLS          28
#define IMPORT_POOL1_MAXPOOL_SLIDING_WINDOW_CHANNELS      16
#define IMPORT_POOL1_MAXPOOL_SLIDING_WINDOW_KERNEL_SIZE_X 2
#define IMPORT_POOL1_MAXPOOL_SLIDING_WINDOW_KERNEL_SIZE_Y 2
#define IMPORT_POOL1_MAXPOOL_SLIDING_WINDOW_STRIDE_X      2
#define IMPORT_POOL1_MAXPOOL_SLIDING_WINDOW_STRIDE_Y      2
#define IMPORT_POOL1_MAXPOOL_SLIDING_WINDOW_PAD_LEFT      0
#define IMPORT_POOL1_MAXPOOL_SLIDING_WINDOW_PAD_RIGHT     0
#define IMPORT_POOL1_MAXPOOL_SLIDING_WINDOW_PAD_TOP       0
#define IMPORT_POOL1_MAXPOOL_SLIDING_WINDOW_PAD_BOTTOM    0

// POOL
#define IMPORT_POOL1_MAXPOOL_POOL_BATCH_SIZE   1
#define IMPORT_POOL1_MAXPOOL_POOL_ROWS         14
#define IMPORT_POOL1_MAXPOOL_POOL_COLS         14
#define IMPORT_POOL1_MAXPOOL_POOL_CHANNELS     16
#define IMPORT_POOL1_MAXPOOL_POOL_KERNEL_SIZE_X 2
#define IMPORT_POOL1_MAXPOOL_POOL_KERNEL_SIZE_Y 2
#define IMPORT_POOL1_MAXPOOL_POOL_FINE         1

/**
 * FUNCTION DEFINITION
 */

void import_pool1_MaxPool(
    stream_t(import_pool1_MaxPool_data_t) in[IMPORT_POOL1_MAXPOOL_COARSE],
    stream_t(import_pool1_MaxPool_data_t) out[IMPORT_POOL1_MAXPOOL_COARSE],
    int mode
);

#undef name
#undef NAME
#endif
