#ifndef PLUS214_OUTPUT_HPP_
#define PLUS214_OUTPUT_HPP_

#define name        Plus214_Output
#define NAME        PLUS214_OUTPUT
#define PLUS214_OUTPUT_ID   0

#include "fork.hpp"
#include "conv.hpp"
#include "accum.hpp"
#include "glue.hpp"
#include "bias.hpp"

#define PLUS214_OUTPUT_BATCH_SIZE    1
#define PLUS214_OUTPUT_ROWS          4
#define PLUS214_OUTPUT_COLS          4
#define PLUS214_OUTPUT_CHANNELS      16
#define PLUS214_OUTPUT_FILTERS       1
#define PLUS214_OUTPUT_COARSE_IN     4
#define PLUS214_OUTPUT_COARSE_OUT    1
#define PLUS214_OUTPUT_COARSE_GROUP  1
#define PLUS214_OUTPUT_KERNEL_SIZE_X 1
#define PLUS214_OUTPUT_KERNEL_SIZE_Y 1

#define PLUS214_OUTPUT_HAS_BIAS 0

// coefficients
#define PLUS214_OUTPUT_WEIGHTS PLUS214_OUTPUT_ROWS*PLUS214_OUTPUT_COLS*PLUS214_OUTPUT_CHANNELS*PLUS214_OUTPUT_FILTERS

// dimensions out
#define PLUS214_OUTPUT_ROWS_OUT     1
#define PLUS214_OUTPUT_COLS_OUT     1
#define PLUS214_OUTPUT_CHANNELS_OUT 1

// define data types
typedef ap_fixed<16,8,AP_RND>    Plus214_Output_input_t;
typedef ap_fixed<16,8,AP_RND>  Plus214_Output_output_t;
typedef ap_fixed<16,8,AP_RND>        Plus214_Output_acc_t;
typedef ap_fixed<16,8,AP_RND>  Plus214_Output_weight_t;
typedef ap_fixed<16,8,AP_RND>  Plus214_Output_biases_t;

// FORK
#define PLUS214_OUTPUT_FORK_BATCH_SIZE   1
#define PLUS214_OUTPUT_FORK_ROWS         1
#define PLUS214_OUTPUT_FORK_COLS         1
#define PLUS214_OUTPUT_FORK_CHANNELS     4
#define PLUS214_OUTPUT_FORK_COARSE       1
#define PLUS214_OUTPUT_FORK_KERNEL_SIZE_X 1
#define PLUS214_OUTPUT_FORK_KERNEL_SIZE_Y 1

// CONV
#define PLUS214_OUTPUT_CONV_BATCH_SIZE   1
#define PLUS214_OUTPUT_CONV_ROWS         1
#define PLUS214_OUTPUT_CONV_COLS         1
#define PLUS214_OUTPUT_CONV_CHANNELS     4
#define PLUS214_OUTPUT_CONV_FILTERS      1
#define PLUS214_OUTPUT_CONV_CHANNELS_PER_GROUP 4
#define PLUS214_OUTPUT_CONV_FILTERS_PER_GROUP  1
#define PLUS214_OUTPUT_CONV_GROUPS       1
#define PLUS214_OUTPUT_CONV_KERNEL_SIZE_X 1
#define PLUS214_OUTPUT_CONV_KERNEL_SIZE_Y 1
#define PLUS214_OUTPUT_CONV_FINE         1
#define PLUS214_OUTPUT_CONV_INTERVAL     1

// ACCUM
#define PLUS214_OUTPUT_ACCUM_BATCH_SIZE         1
#define PLUS214_OUTPUT_ACCUM_ROWS               1
#define PLUS214_OUTPUT_ACCUM_COLS               1
#define PLUS214_OUTPUT_ACCUM_GROUPS             1
#define PLUS214_OUTPUT_ACCUM_CHANNELS           4
#define PLUS214_OUTPUT_ACCUM_FILTERS            1
#define PLUS214_OUTPUT_ACCUM_CHANNELS_PER_GROUP 4
#define PLUS214_OUTPUT_ACCUM_FILTERS_PER_GROUP  1

// GLUE
#define PLUS214_OUTPUT_GLUE_BATCH_SIZE   1
#define PLUS214_OUTPUT_GLUE_ROWS         1
#define PLUS214_OUTPUT_GLUE_COLS         1
#define PLUS214_OUTPUT_GLUE_FILTERS      1
#define PLUS214_OUTPUT_GLUE_FILTERS_PER_COARSE  1
#define PLUS214_OUTPUT_GLUE_COARSE_IN    4
#define PLUS214_OUTPUT_GLUE_COARSE_OUT   1
#define PLUS214_OUTPUT_GLUE_COARSE_GROUP 1

// BIAS
#define PLUS214_OUTPUT_BIAS_BATCH_SIZE   1
#define PLUS214_OUTPUT_BIAS_ROWS         1
#define PLUS214_OUTPUT_BIAS_COLS         1
//#define PLUS214_OUTPUT_BIAS_FILTERS      DIVIDE(PLUS214_OUTPUT_FILTERS, PLUS214_OUTPUT_COARSE_OUT*PLUS214_OUTPUT_WR_FACTOR)
#define PLUS214_OUTPUT_BIAS_FILTERS      1

/**
 * FUNCTION DEFINITION
 */

void Plus214_Output(
    const Plus214_Output_weight_t weights[PLUS214_OUTPUT_COARSE_IN][PLUS214_OUTPUT_COARSE_OUT][DIVIDE(PLUS214_OUTPUT_WEIGHTS,PLUS214_OUTPUT_COARSE_IN*PLUS214_OUTPUT_COARSE_OUT)][1][1],
#if PLUS214_OUTPUT_HAS_BIAS == 1
    const Plus214_Output_biases_t biases[PLUS214_OUTPUT_COARSE_OUT][PLUS214_OUTPUT_BIAS_FILTERS],
#endif
    stream_t(Plus214_Output_input_t) in[PLUS214_OUTPUT_COARSE_IN],
    stream_t(Plus214_Output_output_t) out[PLUS214_OUTPUT_COARSE_OUT],
    int mode
);

#endif
#undef name
#undef NAME
