#ifndef POOLING160_OUTPUT_HPP_
#define POOLING160_OUTPUT_HPP_

#include "sliding_window.hpp"
#include "pool.hpp"

#define name        Pooling160_Output
#define NAME        POOLING160_OUTPUT
#define POOLING160_OUTPUT_ID   0

#define POOLING160_OUTPUT_BATCH_SIZE    1
#define POOLING160_OUTPUT_ROWS          14
#define POOLING160_OUTPUT_COLS          14
#define POOLING160_OUTPUT_CHANNELS      16
#define POOLING160_OUTPUT_COARSE        4
#define POOLING160_OUTPUT_KERNEL_SIZE_X 3
#define POOLING160_OUTPUT_KERNEL_SIZE_Y 3
#define POOLING160_OUTPUT_STRIDE_X      3
#define POOLING160_OUTPUT_STRIDE_Y      3
#define POOLING160_OUTPUT_FINE          1

#define POOLING160_OUTPUT_COARSE_IN    POOLING160_OUTPUT_COARSE
#define POOLING160_OUTPUT_COARSE_OUT   POOLING160_OUTPUT_COARSE

#define POOLING160_OUTPUT_ROWS_OUT     4
#define POOLING160_OUTPUT_COLS_OUT     4
#define POOLING160_OUTPUT_CHANNELS_OUT 16

// define the data type
typedef ap_fixed<16,8,AP_RND> Pooling160_Output_data_t;
typedef Pooling160_Output_data_t Pooling160_Output_input_t;
typedef Pooling160_Output_data_t Pooling160_Output_output_t;

// SLIDING WINDOW
#define POOLING160_OUTPUT_SLIDING_WINDOW_BATCH_SIZE    1
#define POOLING160_OUTPUT_SLIDING_WINDOW_ROWS          14
#define POOLING160_OUTPUT_SLIDING_WINDOW_COLS          14
#define POOLING160_OUTPUT_SLIDING_WINDOW_CHANNELS      4
#define POOLING160_OUTPUT_SLIDING_WINDOW_KERNEL_SIZE_X 3
#define POOLING160_OUTPUT_SLIDING_WINDOW_KERNEL_SIZE_Y 3
#define POOLING160_OUTPUT_SLIDING_WINDOW_STRIDE_X      3
#define POOLING160_OUTPUT_SLIDING_WINDOW_STRIDE_Y      3
#define POOLING160_OUTPUT_SLIDING_WINDOW_PAD_LEFT      0
#define POOLING160_OUTPUT_SLIDING_WINDOW_PAD_RIGHT     0
#define POOLING160_OUTPUT_SLIDING_WINDOW_PAD_TOP       0
#define POOLING160_OUTPUT_SLIDING_WINDOW_PAD_BOTTOM    0

// POOL
#define POOLING160_OUTPUT_POOL_BATCH_SIZE   1
#define POOLING160_OUTPUT_POOL_ROWS         4
#define POOLING160_OUTPUT_POOL_COLS         4
#define POOLING160_OUTPUT_POOL_CHANNELS     4
#define POOLING160_OUTPUT_POOL_KERNEL_SIZE_X 3
#define POOLING160_OUTPUT_POOL_KERNEL_SIZE_Y 3
#define POOLING160_OUTPUT_POOL_FINE         1

/**
 * FUNCTION DEFINITION
 */

void Pooling160_Output(
    stream_t(Pooling160_Output_data_t) in[POOLING160_OUTPUT_COARSE],
    stream_t(Pooling160_Output_data_t) out[POOLING160_OUTPUT_COARSE],
    int mode
);

#undef name
#undef NAME
#endif
