#ifndef POOLING66_OUTPUT_HPP_
#define POOLING66_OUTPUT_HPP_

#include "sliding_window.hpp"
#include "pool.hpp"

#define name        Pooling66_Output
#define NAME        POOLING66_OUTPUT
#define POOLING66_OUTPUT_ID   0

#define POOLING66_OUTPUT_BATCH_SIZE    1
#define POOLING66_OUTPUT_ROWS          28
#define POOLING66_OUTPUT_COLS          28
#define POOLING66_OUTPUT_CHANNELS      8
#define POOLING66_OUTPUT_COARSE        1
#define POOLING66_OUTPUT_KERNEL_SIZE_X 2
#define POOLING66_OUTPUT_KERNEL_SIZE_Y 2
#define POOLING66_OUTPUT_STRIDE_X      2
#define POOLING66_OUTPUT_STRIDE_Y      2
#define POOLING66_OUTPUT_FINE          1

#define POOLING66_OUTPUT_COARSE_IN    POOLING66_OUTPUT_COARSE
#define POOLING66_OUTPUT_COARSE_OUT   POOLING66_OUTPUT_COARSE

#define POOLING66_OUTPUT_ROWS_OUT     14
#define POOLING66_OUTPUT_COLS_OUT     14
#define POOLING66_OUTPUT_CHANNELS_OUT 8

// define the data type
typedef ap_fixed<16,8,AP_RND> Pooling66_Output_data_t;
typedef Pooling66_Output_data_t Pooling66_Output_input_t;
typedef Pooling66_Output_data_t Pooling66_Output_output_t;

// SLIDING WINDOW
#define POOLING66_OUTPUT_SLIDING_WINDOW_BATCH_SIZE    1
#define POOLING66_OUTPUT_SLIDING_WINDOW_ROWS          28
#define POOLING66_OUTPUT_SLIDING_WINDOW_COLS          28
#define POOLING66_OUTPUT_SLIDING_WINDOW_CHANNELS      8
#define POOLING66_OUTPUT_SLIDING_WINDOW_KERNEL_SIZE_X 2
#define POOLING66_OUTPUT_SLIDING_WINDOW_KERNEL_SIZE_Y 2
#define POOLING66_OUTPUT_SLIDING_WINDOW_STRIDE_X      2
#define POOLING66_OUTPUT_SLIDING_WINDOW_STRIDE_Y      2
#define POOLING66_OUTPUT_SLIDING_WINDOW_PAD_LEFT      0
#define POOLING66_OUTPUT_SLIDING_WINDOW_PAD_RIGHT     0
#define POOLING66_OUTPUT_SLIDING_WINDOW_PAD_TOP       0
#define POOLING66_OUTPUT_SLIDING_WINDOW_PAD_BOTTOM    0

// POOL
#define POOLING66_OUTPUT_POOL_BATCH_SIZE   1
#define POOLING66_OUTPUT_POOL_ROWS         14
#define POOLING66_OUTPUT_POOL_COLS         14
#define POOLING66_OUTPUT_POOL_CHANNELS     8
#define POOLING66_OUTPUT_POOL_KERNEL_SIZE_X 2
#define POOLING66_OUTPUT_POOL_KERNEL_SIZE_Y 2
#define POOLING66_OUTPUT_POOL_FINE         1

/**
 * FUNCTION DEFINITION
 */

void Pooling66_Output(
    stream_t(Pooling66_Output_data_t) in[POOLING66_OUTPUT_COARSE],
    stream_t(Pooling66_Output_data_t) out[POOLING66_OUTPUT_COARSE],
    int mode
);

#undef name
#undef NAME
#endif
