<AutoPilot:project xmlns:AutoPilot="com.autoesl.autopilot.project" projectType="C/C++" name="partition_0" top="fpgaconvnet_ip">
    <files>
        <file name="../data/import_conv1first_Conv2D_weights_0.dat" sc="0" tb="1" cflags=" -Wno-unknown-pragmas" csimflags=" -Wno-unknown-pragmas" blackbox="false"/>
        <file name="../data/import_conv1first_Conv2D_biases_0.dat" sc="0" tb="1" cflags=" -Wno-unknown-pragmas" csimflags=" -Wno-unknown-pragmas" blackbox="false"/>
        <file name="../data/import_conv2_Conv2D_weights_0.dat" sc="0" tb="1" cflags=" -Wno-unknown-pragmas" csimflags=" -Wno-unknown-pragmas" blackbox="false"/>
        <file name="../data/import_conv3_Conv2D_weights_0.dat" sc="0" tb="1" cflags=" -Wno-unknown-pragmas" csimflags=" -Wno-unknown-pragmas" blackbox="false"/>
        <file name="../data/import_conv3_Conv2D_biases_0.dat" sc="0" tb="1" cflags=" -Wno-unknown-pragmas" csimflags=" -Wno-unknown-pragmas" blackbox="false"/>
        <file name="../data/import_conv4last_BiasAdd_biases_0.dat" sc="0" tb="1" cflags=" -Wno-unknown-pragmas" csimflags=" -Wno-unknown-pragmas" blackbox="false"/>
        <file name="../data/import_conv4last_BiasAdd_weights_0.dat" sc="0" tb="1" cflags=" -Wno-unknown-pragmas" csimflags=" -Wno-unknown-pragmas" blackbox="false"/>
        <file name="../data/import_conv2_Conv2D_biases_0.dat" sc="0" tb="1" cflags=" -Wno-unknown-pragmas" csimflags=" -Wno-unknown-pragmas" blackbox="false"/>
        <file name="../tb/lenet_tb.cpp" sc="0" tb="1" cflags=" -I../include  -I../data  -I/home/michal/miniconda3/envs/fpgaconvnet/lib/python3.8/site-packages/fpgaconvnet/hls/hardware  -I/home/michal/miniconda3/envs/fpgaconvnet/lib/python3.8/site-packages/fpgaconvnet/hls/hardware/hlslib/include -std=c++11 -fexceptions  -Wno-unknown-pragmas" csimflags=" -Wno-unknown-pragmas" blackbox="false"/>
        <file name="partition_0/src/import_conv1first_Conv2D.cpp" sc="0" tb="false" cflags="-std=c++11 -fexceptions -Ipartition_0/include -Ipartition_0/data -I/home/michal/miniconda3/envs/fpgaconvnet/lib/python3.8/site-packages/fpgaconvnet/hls/hardware -I/home/michal/miniconda3/envs/fpgaconvnet/lib/python3.8/site-packages/fpgaconvnet/hls/hardware/hlslib/include" csimflags="" blackbox="false"/>
        <file name="partition_0/src/import_conv2_Relu.cpp" sc="0" tb="false" cflags="-std=c++11 -fexceptions -Ipartition_0/include -Ipartition_0/data -I/home/michal/miniconda3/envs/fpgaconvnet/lib/python3.8/site-packages/fpgaconvnet/hls/hardware -I/home/michal/miniconda3/envs/fpgaconvnet/lib/python3.8/site-packages/fpgaconvnet/hls/hardware/hlslib/include" csimflags="" blackbox="false"/>
        <file name="partition_0/src/import_conv3_Relu.cpp" sc="0" tb="false" cflags="-std=c++11 -fexceptions -Ipartition_0/include -Ipartition_0/data -I/home/michal/miniconda3/envs/fpgaconvnet/lib/python3.8/site-packages/fpgaconvnet/hls/hardware -I/home/michal/miniconda3/envs/fpgaconvnet/lib/python3.8/site-packages/fpgaconvnet/hls/hardware/hlslib/include" csimflags="" blackbox="false"/>
        <file name="partition_0/src/import_pool1_MaxPool.cpp" sc="0" tb="false" cflags="-std=c++11 -fexceptions -Ipartition_0/include -Ipartition_0/data -I/home/michal/miniconda3/envs/fpgaconvnet/lib/python3.8/site-packages/fpgaconvnet/hls/hardware -I/home/michal/miniconda3/envs/fpgaconvnet/lib/python3.8/site-packages/fpgaconvnet/hls/hardware/hlslib/include" csimflags="" blackbox="false"/>
        <file name="partition_0/src/import_pool2_MaxPool.cpp" sc="0" tb="false" cflags="-std=c++11 -fexceptions -Ipartition_0/include -Ipartition_0/data -I/home/michal/miniconda3/envs/fpgaconvnet/lib/python3.8/site-packages/fpgaconvnet/hls/hardware -I/home/michal/miniconda3/envs/fpgaconvnet/lib/python3.8/site-packages/fpgaconvnet/hls/hardware/hlslib/include" csimflags="" blackbox="false"/>
        <file name="partition_0/src/lenet_top.cpp" sc="0" tb="false" cflags="-std=c++11 -fexceptions -Ipartition_0/include -Ipartition_0/data -I/home/michal/miniconda3/envs/fpgaconvnet/lib/python3.8/site-packages/fpgaconvnet/hls/hardware -I/home/michal/miniconda3/envs/fpgaconvnet/lib/python3.8/site-packages/fpgaconvnet/hls/hardware/hlslib/include" csimflags="" blackbox="false"/>
        <file name="partition_0/src/import_conv3_Conv2D.cpp" sc="0" tb="false" cflags="-std=c++11 -fexceptions -Ipartition_0/include -Ipartition_0/data -I/home/michal/miniconda3/envs/fpgaconvnet/lib/python3.8/site-packages/fpgaconvnet/hls/hardware -I/home/michal/miniconda3/envs/fpgaconvnet/lib/python3.8/site-packages/fpgaconvnet/hls/hardware/hlslib/include" csimflags="" blackbox="false"/>
        <file name="partition_0/src/import_conv1first_Relu.cpp" sc="0" tb="false" cflags="-std=c++11 -fexceptions -Ipartition_0/include -Ipartition_0/data -I/home/michal/miniconda3/envs/fpgaconvnet/lib/python3.8/site-packages/fpgaconvnet/hls/hardware -I/home/michal/miniconda3/envs/fpgaconvnet/lib/python3.8/site-packages/fpgaconvnet/hls/hardware/hlslib/include" csimflags="" blackbox="false"/>
        <file name="partition_0/src/import_conv4last_BiasAdd.cpp" sc="0" tb="false" cflags="-std=c++11 -fexceptions -Ipartition_0/include -Ipartition_0/data -I/home/michal/miniconda3/envs/fpgaconvnet/lib/python3.8/site-packages/fpgaconvnet/hls/hardware -I/home/michal/miniconda3/envs/fpgaconvnet/lib/python3.8/site-packages/fpgaconvnet/hls/hardware/hlslib/include" csimflags="" blackbox="false"/>
        <file name="partition_0/src/import_conv2_Conv2D.cpp" sc="0" tb="false" cflags="-std=c++11 -fexceptions -Ipartition_0/include -Ipartition_0/data -I/home/michal/miniconda3/envs/fpgaconvnet/lib/python3.8/site-packages/fpgaconvnet/hls/hardware -I/home/michal/miniconda3/envs/fpgaconvnet/lib/python3.8/site-packages/fpgaconvnet/hls/hardware/hlslib/include" csimflags="" blackbox="false"/>
    </files>
    <solutions>
        <solution name="solution" status=""/>
    </solutions>
</AutoPilot:project>

